# Generated by Django 4.2.1 on 2023-05-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('content', models.CharField(max_length=500, verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='records/', verbose_name='Превью (изображение)')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('published', models.BooleanField(default=False, verbose_name='Признак публикации')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('name',), 'verbose_name': 'контакт', 'verbose_name_plural': 'контакты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='changed_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
