# Generated by Django 4.2.1 on 2023-06-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'permissions': [('set_published_record', 'Can publish record')], 'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
    ]
